services:
  gateway_service:
    build:
      context: ./gateway_service
      dockerfile: Dockerfile
    container_name: airglow_gateway_service
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - auth_service
      - dag_crud
    networks:
      - airglow_network

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: airglow_auth_service
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./auth_service:/app
    networks:
      - airglow_network

  dag_crud:
    build:
      context: ./dag_crud
      dockerfile: Dockerfile
    container_name: airglow_dag_crud
    env_file:
      - .env
    ports:
      - "8001:8000"
    restart: unless-stopped
    volumes:
      - ./dag_crud:/app
    networks:
      - airglow_network

networks:
  airglow_network:
    driver: bridge
