events {
    worker_connections 1024;
}

http {

    upstream auth_service {
        server auth_service:8000;
    }

    upstream dag_service {
        server dag_crud:8001;
    }

    server {

        listen 80;

        location / {
            return 200 "AirGlow API Gateway Running";
            add_header Content-Type text/plain;
        }

        # Authentication Service
        location /auth/ {
            proxy_pass http://auth_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
}

        # DAG CRUD Service
        location /dags/ {
            proxy_pass http://dag_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /dashboard/ {
            proxy_pass http://dag_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /webhooks/ {
            proxy_pass http://dag_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /health {
            proxy_pass http://dag_service;
        }

    }
}