events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth_service:8000;
    }

    server {
        listen 80;

        location / {
            return 200 "API Gateway is running\n";
            add_header Content-Type text/plain;
        }

        location /auth/ {
            rewrite ^/auth/(.*) /$1 break;
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
